name: Build and deploy Node.js app to Azure Web App - share-a-meal-damian-buskens

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Set up Node.js version
            uses: actions/setup-node@v3
            with:
              node-version: '20.x'

          - name: npm install
            run: |
              npm install
          - name: Zip artifact for deployment
            run: zip release.zip ./* -r

          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v3
            with:
              name: node-app
              path: release.zip

    test:
        runs-on: ubuntu-latest
        needs: build
        env:
            MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_NAME: share_a_meal
            DB_USER: root
            DB_PASSWORD: root
            JWT_KEY: supersecretkey
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip main.zip

            - name: Start MySQL connection from host
              run: |
                  sudo /etc/init.d/mysql start
                  sudo apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.DB_NAME}};"

            - name: Import the database
              run: |
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_NAME}} < share-a-meal.sql
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_NAME}} -e "SHOW TABLES;"

            - name: npm test
              run: |
                  npm test -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_NAME --DB_PORT $DB_PORT

    deploy:
        runs-on: ubuntu-latest
        needs: [test]
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
          - name: Download artifact from build job
            uses: actions/download-artifact@v3
            with:
              name: node-app

          - name: Unzip artifact for deployment
            run: unzip release.zip
      
          - name: Login to Azure
            uses: azure/login@v1
            with:
                client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E4F3A6BFB1140FCB641961B5D2C4EED }}
                tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40539BD452074385A2371C887C56FF29 }}
                subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_623914316D04462A964C774956FA97BF }}

          - name: 'Deploy to Azure Web App'
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
                app-name: 'share-a-meal-damian-buskens'
                slot-name: 'Production'
                package: .
          
  
